### ISSUE TITLE
bug 反馈

### ISSUE THREAD

**Issue by Turing-Wu** [koolshare/ttsoft#1]
1.05 曾经用gfwlist模式可以正常使用，升级到1.06以及1.07 gfwlist模式就无法使用了，不过大陆白名单可以使用，但是无法应对DNS污染。（1.05 gfwlist模式可以防止DNS污染）

**Comment by Turing-Wu** [comment]
1.09 依然无法使用gfwlist模式

**Comment by sadoneli** [comment]
待查

**Comment by sadoneli** [comment]
try 1.1.0
