### ISSUE TITLE
Shadowsocks 运行状态显示不正常

### ISSUE THREAD

**Issue by Dxy00** [koolshare/ttsoft#13]
1.2.2版Shadowsocks已经正常连接，并且可以访问国外被墙网站，运行状态的国外链接依然显示为红叉❌。当前的SS插件尚未加入游戏模式V2，以后更新会加入吗？

**Comment by sadoneli** [comment]
1 链接状态仅供参考
2 暂时不会


2017-06-02 11:00 GMT+08:00 Dxy00 <notifications@github.com>:
