### ISSUE TITLE
菜单错误 1.1.2

### ISSUE THREAD

**Issue by Turing-Wu** [koolshare/ttsoft#2]
域名黑名单

强制走SS的外网ip地址,例如：
baidu.com
koolshare.cn

应该是：“强制走SS的外网域名”才对

**Comment by Turing-Wu** [comment]
还有

域名黑名单

强制走SS的外网ip地址,例如：
baidu.com
koolshare.cn

应该是：“强制走SS的外网域名”才对

**Comment by Turing-Wu** [comment]
还有 1.1.2 gfwlist模式依然无法使用
大陆白名单模式可用，但是  国外链接 一直显示： Problem detected!

**Comment by sadoneli** [comment]
gfwlist我这里可用，请检查下你的dns设定

**Comment by Turing-Wu** [comment]
这个问题很奇怪，我刚开始是可以用gfwlist模式的（节点用的ss），第2天添加了一个ssr节点就不能用gfwlist模式了，后来删除ssr节点的时候所有的ss节点和设置都丢失了。后来尝试过格式化JFFS、以及清空NVRAM，重新安装软件中心。但是就一直不能用gfwlist模式了。
