### ISSUE TITLE
1.1.3 一个影响无线5G的bug，可重现

### ISSUE THREAD

**Issue by Turing-Wu** [koolshare/ttsoft#3]
路由器型号 R7000 

“选择国外DNS” 那里 选 “ss-tunnel" 然后重启路由器，所有设备都无法连接5G频段，只能连2.4G频段。

将设置修改回 dns2socks 或者 pdnsd 然后重启路由器，5G频段恢复正常。

**Comment by jannson** [comment]
难度 udp 影响到了无线的连接？挺奇怪。

**Comment by sadoneli** [comment]
你好，我使用ss-libev，在大陆白名单情况下使用ss-tunnel重启了两次路由器，均未发现你说的情况
