### ISSUE TITLE
gfwlist 模式的问题找到原因了

### ISSUE THREAD

**Issue by Turing-Wu** [koolshare/ttsoft#4]
今天格式化JFFS重新安装软件中心0.1.7版，重新安装了SS，配置的时候抱着试一试的心态，没有修改 “账号设置” 那里默认的 gfwlist 模式 直接点击提交，结果可以正常翻墙。

还以为这个问题解决了。结果查看日志显示：  加载ACL规则：其余主机模式为：大陆白名单模式

原来装好SS第一次配置 “账号设置” 那里默认的 gfwlist模式 你如果不改动它直接点提交，实际上是用的 大陆白名单模式！ 造成 gfwlist 模式 可用的假象！

接下来在  “账号设置” 那里 修改为 大陆白名单模式，点击提交，然后再修改回 gfwlist模式 就不可用了。

实际上gfwlist模式是不可用的。

**Comment by sadoneli** [comment]
1 没有任何配置的时候,进入主界面,在账号设置里除了节点名会显示节点1外其它都是空的,包括模式选项
2 如果你在账号设置内填入节点信息,那么模式时使用你选择的模式的
3 如果没有在账号设置内填入节点信息而是直接添加了一个gfwlist模式的节点,确实会出现你说的问题:账号设置内显示gfwlist模式,而提交显示了大陆白名单模式,这里的显示问题我会修复,强制在进入账号设置页面的时候同步一次这里和访问控制的模式
4 如果手动选一下gfwlist模式,账号设置内的模式时会和访问控制里的模式同步的,我选择gfwlist模式没有任何问题,仍然没法重现你的问题

**Comment by Turing-Wu** [comment]
难道和硬件版本以及固件版本有关？我的硬件是 R7000 ，刷的J大19日编译的固件。
