### ISSUE TITLE
关于各种bug在大神机器上不能重现的疑问

### ISSUE THREAD

**Issue by Turing-Wu** [koolshare/ttsoft#5]
请教一下，诸位大神开发测试不会是用的 Advanced Tomato英文原版固件吧？
如果是的话，那我也换英文原版固件试试。

**Comment by sadoneli** [comment]
是的，我用的是英文原版固件
现在深度怀疑你用了汉化固件，而汉化固件没有dnsmasq的ipset模块支持
所以导致了gfwlist模式不能用，大陆白名单模式能用但是状态显示不正确

你输入命令 `dnsmasq --version`
把输出结果贴上来看看

**Comment by Turing-Wu** [comment]
好的，晚上回去把结果贴上来。

看来 JSMonkey 大 汉化的固件也有坑啊

**Comment by Turing-Wu** [comment]
root@R7000:/tmp/home/root# dnsmasq --version
Dnsmasq version 2.76  Copyright (c) 2000-2016 Simon Kelley
Compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset Tomato-helper auth DNSSEC loop-detect inotify

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.

**Comment by Turing-Wu** [comment]
英文原版的结果好像是一样的
root@R7000:/tmp/home/root# dnsmasq --version
Dnsmasq version 2.76  Copyright (c) 2000-2016 Simon Kelley
Compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6                                                                                         no-Lua TFTP no-conntrack ipset Tomato-helper auth DNSSEC loop-detect inotify

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.

**Comment by Turing-Wu** [comment]
刚刷了英文原版测试，和JSMonkey汉化版一样的结果。

按理说软件中心的插件配置都是保存在JFFS分区的吧？格式化JFFS分区就够了，清不清NVRAM都一样吧？

**Comment by Turing-Wu** [comment]
刷回JSMonkey汉化版反复测试了一下，发现gfwlist模式可用的前提是， “黑白名单” -“域名黑名单”那里不添加任何内容。

一旦自己添加了内容进去之后gfwlist模式就不可用了。

**Comment by Turing-Wu** [comment]
但是使用gfwlist模式肯定是有些漏网之鱼需要自己在域名黑名单那里添加的呀。这个bug很要命啊。

**Comment by Turing-Wu** [comment]
发现大陆白名单模式和gfwlist模式的日志有点不同

大陆白名单模式的日志如下：
【2017年03月27日 22:37:24】: 创建SS配置文件到/jffs/koolshare/ss/ss.json
【2017年03月27日 22:37:24】: 生成cdn加速列表到/tmp/sscdn.conf，加速用的dns：114.114.114.114
【2017年03月27日 22:37:26】: 创建域名黑/白名单软链接到/jffs/configs/dnsmasq.d/wblist.conf
【2017年03月27日 22:37:26】: 创建cdn加速列表软链接/jffs/etc/dnsmasq.d/cdn.conf
【2017年03月27日 22:37:26】: 创建gfwlist的软连接到/jffs/etc/dnsmasq.d/文件夹.

gfwlist模式的日志如下：
【2017年03月27日 22:39:28】: 创建SS配置文件到/jffs/koolshare/ss/ss.json
【2017年03月27日 22:39:28】: 生成cdn加速列表到/tmp/sscdn.conf，加速用的dns：114.114.114.114
【2017年03月27日 22:39:30】: 创建域名黑/白名单软链接到/jffs/configs/dnsmasq.d/wblist.conf
【2017年03月27日 22:39:30】: 创建cdn加速列表软链接/jffs/etc/dnsmasq.d/cdn.conf

为什么大陆白名单模式要 创建gfwlist的软连接，而gfwlis模式反而没有 创建 创建gfwlist的软连接 呢？

**Comment by jannson** [comment]
是不是整反了？你可以自己看看代码找找问题。

**Comment by Turing-Wu** [comment]
宝哥，确实没整反。

至于看代码，让大神见笑了。我的水平也就是看教程复制粘贴，命令行安装卸载软件而已。

之前的RT-N16 （MIPS) Tomato 根据网上各个不完整的教程也就只能搞到全局SS翻墙而已。如果水平再高点能把N16 搞到自动翻墙，估计我也不会换R7000了。

**Comment by Turing-Wu** [comment]
反复测试了几遍，确实没反。这个应该就是gfwlist模式不能使用的原因吧？我贴一下完整日志

【2017年03月28日 08:15:39】: ---------------------- Advanced Tomato 固件 shadowsocks -----------------------
【2017年03月28日 08:15:39】: 删除ss相关的名单配置文件.
【2017年03月28日 08:15:40】: 清除nat-start, wan-start中相关的SS启动命令...
【2017年03月28日 08:15:40】: ---------------------------------------------------------------------------------------
【2017年03月28日 08:15:40】: 使用nslookup方式解析SS服务器的ip地址,解析dns：119.29.29.29
【2017年03月28日 08:15:40】: SS服务器的ip地址解析成功：xx.xx.xx.xx.
【2017年03月28日 08:15:40】: 创建SS配置文件到/jffs/koolshare/ss/ss.json
【2017年03月28日 08:15:40】: 生成cdn加速列表到/tmp/sscdn.conf，加速用的dns：114.114.114.114
【2017年03月28日 08:15:41】: 应用域名黑名单
【2017年03月28日 08:15:42】: 创建域名黑/白名单软链接到/jffs/configs/dnsmasq.d/wblist.conf
【2017年03月28日 08:15:42】: 创建cdn加速列表软链接/jffs/etc/dnsmasq.d/cdn.conf
【2017年03月28日 08:15:42】: 创建gfwlist的软连接到/jffs/etc/dnsmasq.d/文件夹.
【2017年03月28日 08:15:42】: DNS解析方案国外优先，优先解析国外DNS.
【2017年03月28日 08:15:42】: 添加nat-start触发事件...
【2017年03月28日 08:15:42】: 加入开机自动启动...
【2017年03月28日 08:15:42】: 添加ss规则定时更新任务，每天3自动检测更新规则.
【2017年03月28日 08:15:42】: 开启ss-redir进程，用于透明代理.
【2017年03月28日 08:15:42】: 加载TPROXY内核模块！
【2017年03月28日 08:15:42】: 加载nat规则!
【2017年03月28日 08:15:42】: 尝试先清除已存在的iptables规则，防止重复添加
【2017年03月28日 08:15:43】: 先清空已存在的ipset名单，防止重复添加
【2017年03月28日 08:15:43】: 清除重复的ip rule规则.
【2017年03月28日 08:15:43】: 删除ip route规则.
【2017年03月28日 08:15:43】: 创建ipset名单
【2017年03月28日 08:15:43】: 写入iptables规则到nat表中...
【2017年03月28日 08:15:44】: 加载ACL规则：【192.168.1.12】【】:all模式为：不通过SS
【2017年03月28日 08:15:44】: 加载ACL规则：192.168.1.11:80,443模式为：gfwlist模式
【2017年03月28日 08:15:44】: 加载ACL规则：其余主机模式为：大陆白名单模式
【2017年03月28日 08:15:44】: 开启chromecast功能（DNS劫持功能）
【2017年03月28日 08:15:44】: 重启dnsmasq服务...
【2017年03月28日 08:15:44】: 开启dns2socks，监听端口：23456
【2017年03月28日 08:15:45】: ------------------------- shadowsocks 启动完毕 -------------------------


【2017年03月28日 08:18:32】: ---------------------- Advanced Tomato 固件 shadowsocks -----------------------
【2017年03月28日 08:18:32】: 删除ss相关的名单配置文件.
【2017年03月28日 08:18:33】: 清除nat-start, wan-start中相关的SS启动命令...
【2017年03月28日 08:18:33】: 关闭ss-redir进程...
【2017年03月28日 08:18:33】: 关闭ss-local进程:23456端口...
【2017年03月28日 08:18:33】: 关闭dns2socks进程...
【2017年03月28日 08:18:33】: 删除ss规则定时更新任务.
【2017年03月28日 08:18:33】: ---------------------------------------------------------------------------------------
【2017年03月28日 08:18:33】: 使用nslookup方式解析SS服务器的ip地址,解析dns：119.29.29.29
【2017年03月28日 08:18:33】: SS服务器的ip地址解析成功：xx.xx.xx.xx.
【2017年03月28日 08:18:33】: 创建SS配置文件到/jffs/koolshare/ss/ss.json
【2017年03月28日 08:18:33】: 生成cdn加速列表到/tmp/sscdn.conf，加速用的dns：114.114.114.114
【2017年03月28日 08:18:35】: 应用域名黑名单
【2017年03月28日 08:18:35】: 创建域名黑/白名单软链接到/jffs/configs/dnsmasq.d/wblist.conf
【2017年03月28日 08:18:35】: 创建cdn加速列表软链接/jffs/etc/dnsmasq.d/cdn.conf
【2017年03月28日 08:18:35】: DNS解析方案国外优先，优先解析国外DNS.
【2017年03月28日 08:18:35】: 添加nat-start触发事件...
【2017年03月28日 08:18:35】: 加入开机自动启动...
【2017年03月28日 08:18:35】: 添加ss规则定时更新任务，每天3自动检测更新规则.
【2017年03月28日 08:18:35】: 开启ss-redir进程，用于透明代理.
【2017年03月28日 08:18:35】: 加载nat规则!
【2017年03月28日 08:18:35】: 尝试先清除已存在的iptables规则，防止重复添加
【2017年03月28日 08:18:36】: 先清空已存在的ipset名单，防止重复添加
【2017年03月28日 08:18:36】: 清除重复的ip rule规则.
【2017年03月28日 08:18:36】: 删除ip route规则.
【2017年03月28日 08:18:36】: 创建ipset名单
【2017年03月28日 08:18:36】: 写入iptables规则到nat表中...
【2017年03月28日 08:18:37】: 加载ACL规则：【192.168.1.12】【】:all模式为：不通过SS
【2017年03月28日 08:18:37】: 加载ACL规则：192.168.1.11:80,443模式为：gfwlist模式
【2017年03月28日 08:18:37】: 加载ACL规则：其余主机模式为：gfwlist模式
【2017年03月28日 08:18:37】: 开启chromecast功能（DNS劫持功能）
【2017年03月28日 08:18:37】: 重启dnsmasq服务...
【2017年03月28日 08:18:37】: 开启dns2socks，监听端口：23456
【2017年03月28日 08:18:37】: ------------------------- shadowsocks 启动完毕 -------------------------

**Comment by sadoneli** [comment]
https://github.com/koolshare/ttsoft/blob/master/shadowsocks/shadowsocks/ss/start.sh#L527-L534
日志没错的，其实在gfwlist模式下，我没有写日志输出，导致你观察到这个现象

1. 在gfwlist启用的时候，会把/jffs/etc/dnsmasq.d/gfwlist.conf软连接到/jffs/etc/dnsmasq.d
2. 在大陆白名单或者游戏模式启用的时候，如果访问控制里面有主机启用了gfwlist模式，那么也会把/jffs/etc/dnsmasq.d/gfwlist.conf软连接到/jffs/etc/dnsmasq.d

**Comment by sadoneli** [comment]
希望能有办法远程到你的机器，这样应该很快能发现问题

**Comment by Turing-Wu** [comment]
我的QQ 105586306 ，大神是直接连我的路由器吗？那我把路由器的外网控制打开，路由器的公网IP和登录密码用QQ发给你
