### ISSUE TITLE
TT软件中心的2个bug

### ISSUE THREAD

**Issue by Turing-Wu** [koolshare/ttsoft#6]
一个是软件中心自从更新不显示百分比之后，软件中心更新完之后就不会自动跳转了。

第2个就是KoolProxy插件的webUI界面有点小问题，点击查看 状态日志 之后大概1秒左右就会自动跳转回基本设置界面，导致无法查看日志。

**Comment by sadoneli** [comment]
1 https://github.com/koolshare/ttsoft/commit/71e55865414a103f4f13008f8d3906dbde4fc796
已修复，但是得在下次更新软件中心的时候才能看得到了

2 https://github.com/koolshare/ttsoft/commit/68c5fa9b8c9f82ff5946691d629fb33b24ffe5c7
已修复koolproxy log显示跳转问题
