### ISSUE TITLE
Tomato 版 koolproxy 3.3.6 自动更新无效

### ISSUE THREAD

**Issue by Turing-Wu** [koolshare/ttsoft#8]
如题，设置了自动更新，但是没有任何效果。

winSCP登录路由器查看规则文件的修改日期和自己手动更新的时间是对应的，设置的自动更新没有任何效果。

tomato是不是后妈生的呀。

**Comment by jannson** [comment]
不是后妈生的，是现在妈生的。kp 马上要自己内部更新自己，等我们解决问题。
